### MangoHud Configuration

### Legacy overlay options
legacy_layout = false
no_display
toggle_hud = Shift_R+F12

### CPU
cpu_temp
cpu_power
cpu_mhz
cpu_stats

### GPU
gpu_temp
gpu_power
gpu_stats
gpu_name
vulkan_driver

### Memory
ram
vram

### FPS
fps
frametime=0
frame_timing
engine_version
gpu_stats

### Position
position = top-left
table_columns = 2
round_corners = 10.0

### Colors
cpu_color = 2ACFED
gpu_color = 2ACFED
vram_color = AD64C9
ram_color = C266D3
engine_color = 2ACFED
frametime_color = 00FF00
media_player_color = BD93F9

### Background
background_alpha = 0.4
background_color = 020202
alpha = 0.8

### Font
font_size = 24
font_size_text = 20
font_size_small = 16
no_large_font

### Misc
toggle_logging = Shift_R+F2
toggle_hud_position = Shift_R+F1
